# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{curb-openuri}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Shterenzon"]
  s.date = %q{2010-11-10}
  s.description = %q{open-uri drop-in replacement that uses curb}
  s.email = %q{romanbsd@yahoo.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION.yml",
     "curb-openuri.gemspec",
     "lib/curb_openuri.rb",
     "lib/curl_agent.rb",
     "spec/curb_openuri_spec.rb",
     "spec/curl_agent_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/romanbsd/curb-openuri}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{open-uri drop-in replacement that uses curb}
  s.test_files = [
    "spec/curb_openuri_spec.rb",
     "spec/curl_agent_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<curb>, [">= 0.1.4"])
    else
      s.add_dependency(%q<curb>, [">= 0.1.4"])
    end
  else
    s.add_dependency(%q<curb>, [">= 0.1.4"])
  end
end

